# Page settings
baseURL = "localhost:1313"
#baseURL = "http://example.org/"
title = "Pyros Dev"
languageCode = "en-us"
theme = "elate"

[params]
  
  custom_css = ["css/elateCustom.css"]

  # Meta
  author = "XorfacX"
  description = ""
  email = "dev@yros.info"
  # Navigation
  [params.navigation]
    brand = "Pyros"
    home = "What"
    work = "How"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "A software layer on top of the ROS framework"
    subtitle = 'interface your ROS systems with anything and everything!'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = ""
    description = "A standard python dev dynamic workflow => no generation, compilation time wasted)"
    url = "#"
    button = ""
    icon = "icon-bulb"
    img = "img_7.jpg"
    
  [[params.intro.item]]
    title = ""
    description = "Standard python packages, potentially leveraging NNNNN existing packages on PyPI"
    url = "#"
    button = ""
    icon = "icon-bulb"
    img = "img_7.jpg"
    
  [[params.intro.item]]
    title = ""
    description = "Any existing Cloud REST Services (via HTTP)"
    url = "#"
    button = ""
    icon = "icon-bulb"
    img = "img_7.jpg"
    
  [[params.intro.item]]
    title = ""
    description = "Any existing Frontend Application and GUI (via HTTP)"
    url = "#"
    button = ""
    icon = "icon-bulb"
    img = "img_7.jpg"
    
  [[params.intro.item]]
    title = ""
    description = "Any existing IoT infrastructure (via MQTT, RIOT, etc.)"
    url = "#"
    button = ""
    icon = "icon-bulb"
    img = "img_7.jpg"


  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "How"
    description = "Pyros is a distributed framework, relying on standard protocols, so you can can come up with any distributed architecture that fit your needs!"
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "archiREST"
      title = "Robots accessing REST micro services on the cloud"
      subtitle = "like http://gocart.yujinrobot.com/"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "archiMonitor"
      title = "Controling and Monitoring remote robots"
      subtitle = "like https://flytbase.com/"
      
    [[params.work.row]]
      img = "work_2.jpg"
      alt = "archiIDE"
      title = "Do your robot application development in a standard dynamic IDE"
      subtitle = "like PyCharm"
      
    [[params.work.row]]
      img = "work_2.jpg"
      alt = "archiMobile"
      title = "Controling a robot from a webapp on your mobile phone"
      subtitle = ""
      
    [[params.work.row]]
      img = "work_2.jpg"
      alt = "archiCustom"
      title = "Custom architecture"
      subtitle = "and much more !"


  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    address = false
    map = false
    form = true
    title = "Get in touch"
    description = "Looks interesting ? Want to know more ? Contact us !"
    
    # Available icons: http://simplelineicons.com/
    #details = [
    #    ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
    #    ["icon-phone", "(123) 465-6789"],
    #    ["icon-envelope", "info@freehtml5.co"],
    #    ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
    #  ]

    name = "Name"
    email = "Email"
    #phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Pyros Dev'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"]
      ]
